name: modify_readme_workflow
on:
  push:
    branches:
      - "github_action_readme"
jobs:
  test-execution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Jest test
        id: test 
        workdir: ./test
        run: npm install jest && npm test
  Change_Readme:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [test-execution]
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Action Readme"
        uses: ./.github/actions/mod_readme
        with:
          frase_positiva: "bender/vamoss!!/salio_bien_el_test"
          frase_negativa: "cryingfloor/casi.../error_tremendo"
          resultado_tests: ${{ needs.test-execution.result }}
      - name: "Push Readme"
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: "Vicent Esteve Ferre"
          author_email: "esteve.ferre.vicent@gmail.com"
          message: "Readme Updated succesfully"
          push: true